version: 0.0
os: linux

files:
- source: /
  destination: /home/ec2-user/app

hooks:
  BeforeInstall:
  - location: permissions.sh
    timeout: 60
    runas: root

  ApplicationStart:
  - location: start.sh
    timeout: 60
    runas: ec2-user
